### ISSUE TITLE
Run LambdaGuard in Lambda

### ISSUE THREAD

**Issue by aaronwbrown** [Skyscanner/LambdaGuard#14]
## Goal
Deploy LambdaGuard as a Lambda across all regions using CloudFormation StackSets. 
## Issue
After reading through the code, unless I am mistaken, it seems that the project depends on the presence of AWS credentials being present. 
## Contribution
If my understanding is indeed correct, would you accept a PR that decouples the need for credentials, and allow for use of IAM permissions from within the Lambda Runtime?
## Thanks!
Thank you for this tool, and for your consideration.

**Comment by adeptex** [comment]
hey @aaronwbrown thanks for posting!

If you are deploying LambdaGuard as a Lambda you are always running the risk of timing out, because Lambdas are limited to 15mins of execution time. It is better to deploy it as a Batch, which will be a lot more reliable. 

Nonetheless, your contribution regarding using IAM instead of creds sounds interesting and useful. PR is welcome :]

Closing this issue for now. Thank you for using the tool and your future contributions :+1:

**Comment by aaronwbrown** [comment]
Thanks, @adeptex! I'll look through the contribution guidelines. :)

**Comment by lkolchin** [comment]
@aaronwbrown - Did you get to doing any of that? I'm keen to see Lambdaguard running in Lambda....would be a great way to trigger it on deployment of a new version.
Better yet - if it could post findings to SecurityHub it's be awesome.
