### ISSUE TITLE
Multi account reports

### ISSUE THREAD

**Issue by TheFlexican** [Skyscanner/LambdaGuard#28]
Hi,
Not an issue, more a question. Looking for some information.
I'm running this against multiple accounts, output saved into separate directories.
I was wondering, if it would be possible, to have lambdaguard not only write to the output directory, but also updating a central location, where we would have a report for all accounts into one.
I guess it should be possible, is this something you are planning on maybe? 

Thank you!

**Comment by adeptex** [comment]
hi @TheFlexican, you can specify output directory like so: `lambdaguard --output /tmp/$accountNumber` and just loop through your accounts.

I'm afraid the functionality you are asking for is a kind of vulnerability management solution, which is out of scope for this tool. The intention was to provide nice JSON docs that can be easily parsed or uploaded to such a vuln management server. 

I will close this issue since I think I answered your question. Please feel free to open a new one if needed! Cheers
